### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by kewp** [xtao-org/jsonhilo#5]
hello.

i'm trying to process a list of json objects, an array ... a huge list ... but i can't seem to get your lib to await:

```ts
let obj, key;

  const stream = JsonHigh({
    openObject: () => obj = {},
    closeObject: async () => await process(obj),
    key: (_key) => key = _key,
    value: (value) => obj[key] = value
  })
```

is that right? i'm not sure you are awaiting these functions ...

here is how i'm processing the chunks:

```ts
let done = false;
  do {
    const result = await inputReader.read();
    done = result.done;

    if (result.value) {
      stream.chunk(decoder.decode(result.value));
      count += 1;
    }
  } while (!done);
```

though ... i guess i would need to `await stream.chunk` ... ?

**Comment by kewp** [comment]
hmm ok i think i've solved it by just creating a list of promises

```ts
const promises = [];

  const stream = JsonHigh({
    openObject: () => obj = {},
    closeObject: () => promises.push(process(obj)),
    key: (_key) => key = _key,
    value: (value) => obj[key] = value
  })
```

and then after processing all the chunks I just wait for them to finish:

```ts
await Promise.all(promises);
```

i hope that works with millions of entries!

is there a better way to do it?

**Comment by djedr** [comment]
Yeah, you seem to have solved it. The library does not use async-await so it can fit into all kinds of environments.

The way you demonstrated here will only work if you have a flat collection of objects with primitive values.

For anything more complex, you may want to check out https://github.com/xtao-org/jsonstrum -- it's a wrapper around JsonHilo that does more or less what you are trying to do.

Hope this helps. Let me know if you run into any more issues.

Cheerio!

**Comment by kewp** [comment]
For anyone struggling with this in future: trying to process millions of promises did not work, Deno grew to use nearly 2gigs of ram and never seemed to complete. Running through the promises in chunks did work though:

```ts
let promises = [];
let done = false;
  let count = 0;
  do {
    const result = await inputReader.read();
    done = result.done;

    if (result.value) {
      stream.chunk(decoder.decode(result.value));
      count += 1;
    }

    if (count % 1000 == 0) {
      console.log(`In progress. Read ${count} chunks`);
      await Promise.all(promises);
      promises = [];
    }
  } while (!done);

  await Promise.all(promises);

  console.log(`All done. Read ${count} chunks`);
```

That worked with a 500+meg json file with nearly 3 million objects inside.
